services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - homeassistant_data:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    networks:
      hostproxy:
        ipv4_address: 10.10.10.10

volumes:
  homeassistant_data:

networks:
  hostproxy:
    name: hostproxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
